# [이팝콘 데이터팀 2021 신입 DS/DA 채용 python basic coding test]

- coding test의 목적은 기본 개념의 이해와 그를 표현하는 coding style을 보고자 함입니다. <span style="color:red"> (**code가 제출물**입니다. 결과가 아닌)   </span>
- 문제 풀이시 검색의 활용을 권장합니다. (모든 문제는 적절히 검색만 하면 모두 답을 찾을 수 있습니다.)
- 가능한 pythonic한 code로 작성해 주시길 바랍니다.

# 1. Data frame basic (5 points)

- 문제. 아래와 같은 dataframe이 주어졌을 때, list type column "y"의 값이 모두 짝수인 row만 골라내는 code

- hint 
    - apply lambda 
    - modulo operator
    - all(list)

```python
import pandas as pd

x = [ 'a', 'b', 'c', 'd', 'e']
y = [
    [1, 2, 3, 4, 5],
    [2, 4],
    [2, 4, 6, 8, 10],
    [1, 3, 5],
    [10]
]
df = pd.DataFrame({'x' : x, 'y' : y})
df_even_y = ... # code here (should be 1 line)

print('\ndf given')
print(df)
print('\ndf result')
print(df_even_y)

df given
   x                 y
0  a   [1, 2, 3, 4, 5]
1  b            [2, 4]
2  c  [2, 4, 6, 8, 10]
3  d         [1, 3, 5]
4  e              [10]

df result
   x                 y
1  b            [2, 4]
2  c  [2, 4, 6, 8, 10]
4  e              [10]

```

# 답안

In [1]:
import pandas as pd
import numpy as np  # 추가

x = [ 'a', 'b', 'c', 'd', 'e']
y = [
    [1, 2, 3, 4, 5],
    [2, 4],
    [2, 4, 6, 8, 10],
    [1, 3, 5],
    [10]
]
df = pd.DataFrame({'x' : x, 'y' : y})
df_even_y = df[[all(np.array(x)%2-1) for x in df['y']]]  # answer code here (should be 1 line)

print('\ndf given')
print(df)
print('\ndf result')
print(df_even_y)

df given
   x                 y
0  a   [1, 2, 3, 4, 5]
1  b            [2, 4]
2  c  [2, 4, 6, 8, 10]
3  d         [1, 3, 5]
4  e              [10]

df result
   x                 y
1  b            [2, 4]
2  c  [2, 4, 6, 8, 10]
4  e              [10]

# 2. dict comprehension (5 points)

- 문제. <span style="color:red"> dict comprehension </span>을 이용하여 주어진 list of string으로부터 {문자열 : 문자열의 길이} 형태의 dictionary를 생성하는 <span style="color:red"> 1 line code </span>

```python
list_of_string = ['1234', 'ab', '가나다', '']
dict_of_string = ... # code here (should be 1 line)

print('list_of_string', list_of_string)
print('dict_of_string', dict_of_string)

list_of_string ['1234', 'ab', '가나다', '']
dict_of_string {'1234': 4, 'ab': 2, '가나다': 3, '': 0}
```

# 답안

In [2]:
list_of_string = ['1234', 'ab', '가나다', '']
dict_of_string = {x:len(x) for x in list_of_string}  # answer code here (should be 1 line)

In [3]:
# 결과 
print('list_of_string', list_of_string)
print('dict_of_string', dict_of_string)

list_of_string ['1234', 'ab', '가나다', '']
dict_of_string {'1234': 4, 'ab': 2, '가나다': 3, '': 0}

# 3. REGEX (5 points)

- 문제. 주어진 문자열에서 1개 이상의 공란이 발견되면 단 1개의 공란으로 치환하는 function을 완성하시오.
- hint
    - re.sub 


```python

import re

def squeeze_spaces(string):
    pattern = ... # code here (should be 1 line)
    replace = ... # code here (should be 1 line)
    result = ... # code here (should be 1 line)
    
    return result

string = 'ab c \t d             e'
print(string, '==>', squeeze_spaces(string))

ab c 	 d             e ==> ab c d e

```

# 답안

In [4]:
import re

def squeeze_spaces(string):
    pattern = '[\s]+'                                       # answer code here (should be 1 line)
    replace =  ' '                                            # answer code here (should be 1 line)
    result =  re.sub(pattern,replace,string) # answer code here (should be 1 line)

    return result

string = 'ab c \t d             e'
print(string, '==>', squeeze_spaces(string))

ab c 	 d             e ==> ab c d e

# 4. Data frame basic (10 points)

온라인 쇼핑몰의 상품 데이터가 아래와 같이 주어졌다.
- 3개의 columns의 의미는 다음과 같다
    - item_doc_id : 상품의 id
    - goods_name : 상품의 이름
    - goods_cate : 상품의 카테고라
    
- 온라인 쇼핑몰에서는 하나의 상품이 다수의 카테고리를 가질 수도 있는데 이를 세미콜론 ";"으로 구분했다고 가정하자
    - 'TV쇼핑>TV쇼핑 화장품/이미용>화장품/향수>기초스킨케어;(#M)뷰티>화장품/향수>클렌징>기획세트' 는 2개의 카테고리를 가지고 있다는 의미이다
        - cate1 = "TV쇼핑>TV쇼핑 화장품/이미용>화장품/향수>기초스킨케어"
        - cate2 = "뷰티>화장품/향수>클렌징>기획세트"
        - (#M) : main cate임을 표시. 반드시 개별 cate의 처음에 나옴

- 문제1: 해당 상품이 몇 개의 카테고리를 가지고 있는지를 'n_cate' column에 추가하시오
- 문제2: 해당 상품의 main cate를 분리해 내고 (#M)을 삭제하여 'main_cate' column에 추가하시오
    - main cate는 반드시 1개만 존재한다고 가정함
    - main cate가 없거나 다수개가 존재할 때의 처리는 하지 않음

```python
import pandas as pd

item_doc_id = [
 'H_GSSHOP_41513',
 'H_CJmall_1109',
 'H_GSSHOP_41512',
 'H_CJmall_29185',
 'H_Nsmall_45598'
]

goods_name = [
 '삼성 건조기 그랑데 16kg DV16T8520BW 화이트',
 '최저가] 룰루랩 페이스캔랩 초미세파우더 비타민 클렌저 3개',
 '삼성 건조기 그랑데 16kg 패키지DV16T8520BW + WF21T6000KW 화이트',
 '[최신상&무선] 도깨비방망이 CHB2000',
 '휴롬 이지원액기 '
]

goods_cate =[
 'GSSHOP > TV상품 > GS SHOP LIVE > 가전/디지털 > 세탁기/건조기/청소기;GSSHOP > GS MY SHOP > TV쇼핑 > 편성표 > 4/10 Sat > 19:29~20:29;가전/디지털>생활가전>건조기;(#M)TV상품>GS SHOP LIVE>가전/디지털>세탁기/건조기/청소기',
 'TV쇼핑>TV쇼핑 화장품/이미용>화장품/향수>기초스킨케어;(#M)뷰티>화장품/향수>클렌징>기획세트',
 'GSSHOP > TV상품 > GS SHOP LIVE > 가전/디지털 > 세탁기/건조기/청소기;가전/디지털>생활가전>건조기;(#M)TV상품>GS SHOP LIVE>가전/디지털>세탁기/건조기/청소기',
 '(#M)가전/디지털>주방가전>믹서/분쇄기>핸드블렌더',
 'Nsmall >FOOD & HEALTH >TV쇼핑 >가전 >생활가전 >믹서기;Nsmall >가정의달 오!쇼핑축제 >가족만찬 >주방/가전;Nsmall >가정의달 오!쇼핑축제 >주간특가 >주간특가;Nsmall >해피딜 >금주의특가;Nsmall >가정의달 오!쇼핑축제 >홈;(#M)Nsmall >가정의달 오!쇼핑축제 >가족만찬']

goods = pd.DataFrame({'item_doc_id':item_doc_id, 'goods_name':goods_name, 'goods_cate':goods_cate})
goods['n_cate'] = ... # code here (should be 1 line)
goods['main_cate'] = ... # code here (should be 1 line)



number of categories
      item_doc_id  n_cate
0  H_GSSHOP_41513       4
1   H_CJmall_1109       2
2  H_GSSHOP_41512       3
3  H_CJmall_29185       1
4  H_Nsmall_45598       6

main category
      item_doc_id                             main_cate
0  H_GSSHOP_41513  TV상품>GS SHOP LIVE>가전/디지털>세탁기/건조기/청소기
1   H_CJmall_1109                    뷰티>화장품/향수>클렌징>기획세트
2  H_GSSHOP_41512  TV상품>GS SHOP LIVE>가전/디지털>세탁기/건조기/청소기
3  H_CJmall_29185              가전/디지털>주방가전>믹서/분쇄기>핸드블렌더
4  H_Nsmall_45598             Nsmall >가정의달 오!쇼핑축제 >가족만찬

```

# 답안

In [5]:
import pandas as pd

item_doc_id = [
 'H_GSSHOP_41513',
 'H_CJmall_1109',
 'H_GSSHOP_41512',
 'H_CJmall_29185',
 'H_Nsmall_45598'
]

goods_name = [
 '삼성 건조기 그랑데 16kg DV16T8520BW 화이트',
 '최저가] 룰루랩 페이스캔랩 초미세파우더 비타민 클렌저 3개',
 '삼성 건조기 그랑데 16kg 패키지DV16T8520BW + WF21T6000KW 화이트',
 '[최신상&무선] 도깨비방망이 CHB2000',
 '휴롬 이지원액기 '
]

goods_cate =[
 'GSSHOP > TV상품 > GS SHOP LIVE > 가전/디지털 > 세탁기/건조기/청소기;GSSHOP > GS MY SHOP > TV쇼핑 > 편성표 > 4/10 Sat > 19:29~20:29;가전/디지털>생활가전>건조기;(#M)TV상품>GS SHOP LIVE>가전/디지털>세탁기/건조기/청소기',
 'TV쇼핑>TV쇼핑 화장품/이미용>화장품/향수>기초스킨케어;(#M)뷰티>화장품/향수>클렌징>기획세트',
 'GSSHOP > TV상품 > GS SHOP LIVE > 가전/디지털 > 세탁기/건조기/청소기;가전/디지털>생활가전>건조기;(#M)TV상품>GS SHOP LIVE>가전/디지털>세탁기/건조기/청소기',
 '(#M)가전/디지털>주방가전>믹서/분쇄기>핸드블렌더',
 'Nsmall >FOOD & HEALTH >TV쇼핑 >가전 >생활가전 >믹서기;Nsmall >가정의달 오!쇼핑축제 >가족만찬 >주방/가전;Nsmall >가정의달 오!쇼핑축제 >주간특가 >주간특가;Nsmall >해피딜 >금주의특가;Nsmall >가정의달 오!쇼핑축제 >홈;(#M)Nsmall >가정의달 오!쇼핑축제 >가족만찬']


goods = pd.DataFrame({'item_doc_id':item_doc_id, 'goods_name':goods_name, 'goods_cate':goods_cate})

In [6]:
goods['n_cate'] = [len(list(x.split(';'))) for x in goods_cate] # answer code here (should be 1 line)
goods['main_cate'] = [y[4:] for x in list(goods.goods_cate.str.split(';')) for y in x if y.startswith('(#M)')]   # answer code here (should be 1 line)

In [7]:
goods

,item_doc_id,goods_name,goods_cate,n_cate,main_cate
0,H_GSSHOP_41513,삼성 건조기 그랑데 16kg DV16T8520BW 화이트,GSSHOP > TV상품 > GS SHOP LIVE > 가전/디지털 > 세탁기/건조...,4,TV상품>GS SHOP LIVE>가전/디지털>세탁기/건조기/청소기
1,H_CJmall_1109,최저가] 룰루랩 페이스캔랩 초미세파우더 비타민 클렌저 3개,TV쇼핑>TV쇼핑 화장품/이미용>화장품/향수>기초스킨케어;(#M)뷰티>화장품/향수>...,2,뷰티>화장품/향수>클렌징>기획세트
2,H_GSSHOP_41512,삼성 건조기 그랑데 16kg 패키지DV16T8520BW + WF21T6000KW 화이트,GSSHOP > TV상품 > GS SHOP LIVE > 가전/디지털 > 세탁기/건조...,3,TV상품>GS SHOP LIVE>가전/디지털>세탁기/건조기/청소기
3,H_CJmall_29185,[최신상&무선] 도깨비방망이 CHB2000,(#M)가전/디지털>주방가전>믹서/분쇄기>핸드블렌더,1,가전/디지털>주방가전>믹서/분쇄기>핸드블렌더
4,H_Nsmall_45598,휴롬 이지원액기,Nsmall >FOOD & HEALTH >TV쇼핑 >가전 >생활가전 >믹서기;Nsm...,6,Nsmall >가정의달 오!쇼핑축제 >가족만찬

# 5. Array Split (10 points)

- 문제1. list of int가 주어졌을 때, 5개의 sub array로 분리하는 code. (단, 각 array는 균등한 수의 elements를 포함해야 함.)
- 문제2. list of int가 주어졌을 때, elements의 수가 균등하게 5개 정도인 sub array로 분리하는 code. 
- 균등이라 함은 반드시 갯수가 동일하지는 않아도 대체적으로 비슷한 수준을 의미함
- hint
    - numpy array split 
    - integer divide operator (//)

```python
import numpy as np
list_of_int = list(range(10, 99))

sub_array1 = ... # 문제1. code here  (should be 1 line) 
sub_array2 = ... # 문제2. code here  (should be 1 line) 

print('list_of_int\n', list_of_int)

print('\nsub_array1')
[print(sub) for sub in sub_array1]

print('\nsub_array2')
[print(sub) for sub in sub_array2]

list_of_int
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]

sub_array1
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]
[28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]
[46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]
[64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81]
[82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98]

sub_array2
[10 11 12 13 14 15]
[16 17 18 19 20 21]
[22 23 24 25 26 27]
[28 29 30 31 32 33]
[34 35 36 37 38]
[39 40 41 42 43]
[44 45 46 47 48]
[49 50 51 52 53]
[54 55 56 57 58]
[59 60 61 62 63]
[64 65 66 67 68]
[69 70 71 72 73]
[74 75 76 77 78]
[79 80 81 82 83]
[84 85 86 87 88]
[89 90 91 92 93]
[94 95 96 97 98]
```

# 답안

In [8]:
import numpy as np
list_of_int = list(range(10, 99))

sub_array1 = np.array_split(list_of_int, 5)                             # 문제1. answer code here  (should be 1 line) 
sub_array2 = np.array_split(list_of_int, len(list_of_int)//5) # 문제2. answer code here  (should be 1 line) 

print('list_of_int\n', list_of_int)

print('\nsub_array1')
[print(sub) for sub in sub_array1]

print('\nsub_array2')
[print(sub) for sub in sub_array2]

list_of_int
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]

sub_array1
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]
[28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]
[46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]
[64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81]
[82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98]

sub_array2
[10 11 12 13 14 15]
[16 17 18 19 20 21]
[22 23 24 25 26 27]
[28 29 30 31 32 33]
[34 35 36 37 38]
[39 40 41 42 43]
[44 45 46 47 48]
[49 50 51 52 53]
[54 55 56 57 58]
[59 60 61 62 63]
[64 65 66 67 68]
[69 70 71 72 73]
[74 75 76 77 78]
[79 80 81 82 83]
[84 85 86 87 88]
[89 90 91 92 93]
[94 95 96 97 98]

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

# 6. divide, manipulate and join (15 points)

name, age 2개의 columns를 가진 Dataframe에 대해서 
주어진 function adult_check(df)을 사용하여 adult column을 추가하시요.
- 문제1. 주어진 data frame을 row가 10개를 초과하지 않도록 균등하게 분할하여 list of data frame으로 만드시오.
- 문제2. 분할된 data frame들을 각각 adult_check를 수행하고 그 결과를 다시 붙인후에(concat) 원본의 data frame과 동일한 순서로 복귀시키시오.


- function adult_check을 반드시 사용해야 하며 수정하면 안됨.
- 최종 결과 Dataframe은 입력 Dataframe과 동일한 순서이어야 함.
- 필요시 names package를 install하고 실행하세요. (pip install)

- hint
    - numpy array split
    - pandas dataframe concat
    - pandas dataframe sort by index


```python
import pandas as pd
import numpy as np
import names
import random 

rows = 253
max_size = 10

def adult_check(df):
    '''
    주어진 df에 대해서 adult column을 추가하고 나이순으로 정렬해서 리턴하는 function.
    한번에 10개 까지만 처리 가능한 것으로 가정함.
    주의 : 이 function은 수정하면 안됨!!
    '''
    
    if len(df) > max_size:
        raise Exception('data frame too big to process')

    df.loc[df.index, 'adult'] = df.age >= 19
    
    return df.sort_values('age')


print('data frame input')
df = pd.DataFrame(
    {
        'name' : [ names.get_full_name() for i in range(rows) ], 
        'age' : [ random.randint(0, 59) for i in range(rows) ]
    }
)
print(df)

print('\ndata frame split')
df_split = ... # 문제1. code here  (1 line으로 작성하면 더 좋음)
print(df_split[0])
print(df_split[-1])

print('\ndata frame result')
result = ... # 문제2. code here  (1 line으로 작성하면 더 좋음)
print(result)

data frame input
                    name  age
0           David Flythe   13
1        Martha Hirneise   49
2          Estelle White   55
3         Melody Jackson   36
4           Brian Moreno   25
..                   ...  ...
248           Mary Olsen   56
249        Loretta Scott   35
250  Philip Karathanasis   14
251           Heidi Rice   46
252     Bernadine Pillar    3

[253 rows x 2 columns]

data frame split
                name  age
0       David Flythe   13
1    Martha Hirneise   49
2      Estelle White   55
3     Melody Jackson   36
4       Brian Moreno   25
5      Lillie Walker    7
6     Estelle George   53
7      Muriel Wilkes   40
8  Brandi Zumbrunnen   12
9    Michael William   38
                    name  age
244           Jason Cave   12
245            Elena Ivy   43
246    Dorothy Edwardson    3
247        Nathan Bowell   16
248           Mary Olsen   56
249        Loretta Scott   35
250  Philip Karathanasis   14
251           Heidi Rice   46
252     Bernadine Pillar    3

data frame result
                    name  age  adult
0           David Flythe   13  False
1        Martha Hirneise   49   True
2          Estelle White   55   True
3         Melody Jackson   36   True
4           Brian Moreno   25   True
..                   ...  ...    ...
248           Mary Olsen   56   True
249        Loretta Scott   35   True
250  Philip Karathanasis   14  False
251           Heidi Rice   46   True
252     Bernadine Pillar    3  False

[253 rows x 3 columns]

```

# 답안

In [9]:
import pandas as pd
import numpy as np
import names
import random 
import math

rows = 253
max_size = 10

def adult_check(df):
    '''
    주어진 df에 대해서 adult column을 추가하고 나이순으로 정렬해서 리턴하는 function.
    한번에 10개 까지만 처리 가능한 것으로 가정함.
    주의 : 이 function은 수정하면 안됨!!
    '''

    if len(df) > max_size:
        raise Exception('data frame too big to process')

    df.loc[df.index, 'adult'] = df.age >= 19

    return df.sort_values('age')


print('data frame input')
df = pd.DataFrame(
    {
        'name' : [ names.get_full_name() for i in range(rows) ], 
        'age' : [ random.randint(0, 59) for i in range(rows) ]
    }
)
print(df)

print('\ndata frame split')

df_split = np.array_split(df, (len(df)//9))     # 문제1. answer code here  (1 line으로 작성하면 더 좋음)
print(df_split[0])
print(df_split[-1])

print('\ndata frame result')
result = pd.concat([adult_check(x) for x in df_split]).sort_index(ascending=True)  # 문제2. answer code here  (1 line으로 작성하면 더 좋음)
print(result)

data frame input
                   name  age
0    Jacqueline Johnson   47
1           Thelma Cook   52
2          Sal Petersen   45
3      Jennifer Dudasik   24
4     Charles Velazquez   52
..                  ...  ...
248         Danny Salas   31
249     Meredith Talley   36
250         Nancy Pynes   59
251   Carmen Hospelhorn   37
252         Anna Milton   59

[253 rows x 2 columns]

data frame split
                 name  age
0  Jacqueline Johnson   47
1         Thelma Cook   52
2        Sal Petersen   45
3    Jennifer Dudasik   24
4   Charles Velazquez   52
5      Herbert Spivey   34
6        Janet Werner   42
7   Christina Morales   59
8     Thomas Hastings   13
9       Laurie Hiller   45
                       name  age
244           Douglas Cagle   55
245          Francis Linder   37
246           Frank Ramaker   57
247  Christopher Montgomery    5
248             Danny Salas   31
249         Meredith Talley   36
250             Nancy Pynes   59
251       Carmen Hospelhorn   37
252             Anna Milton   59

data frame result
                   name  age  adult
0    Jacqueline Johnson   47   True
1           Thelma Cook   52   True
2          Sal Petersen   45   True
3      Jennifer Dudasik   24   True
4     Charles Velazquez   52   True
..                  ...  ...    ...
248         Danny Salas   31   True
249     Meredith Talley   36   True
250         Nancy Pynes   59   True
251   Carmen Hospelhorn   37   True
252         Anna Milton   59   True

[253 rows x 3 columns]

# 7. iterables (15 points)

주어진 집합 a, b, ab에 대해서
- 문제1. a, b를 이용하여 a의 모든 원소와 b의 모든 원소의 결합으로 만들어진 집합 AB를 생성하시오
    - AB는 ab와 동일해야 한다.
- 문제2. 집합 AB를 다시 분해야여 집합 A, B를 생성하시오.
    - A는 a와 동일하고 B는 b와 동일해야 한다.
- hint
    - product
    - zip and *
    
```python
from itertools import product

a = set(['x', 'y'])
b = set([1, 2, 3, 4])
ab = set([('x', 1), ('x', 2), ('x', 3), ('x', 4), ('y', 1), ('y', 2), ('y', 3), ('y', 4)])

AB = ... # 문제1. code here (should be 1 line using a and b)
A, B = ... # 문제2. code here (should be 1 line using AB)

print(f'ab == AB : {ab == AB}')
print(f'a == A : {a == A}')
print(f'b == B : {b == B}')

print(A)
print(B)
print(AB)

ab == AB : True
a == A : True
b == B : True
{'y', 'x'}
{1, 2, 3, 4}
{('y', 4), ('x', 4), ('x', 1), ('y', 3), ('x', 3), ('y', 2), ('x', 2), ('y', 1)}

```

# 답안

In [10]:
from itertools import product

a = set(['x', 'y'])
b = set([1, 2, 3, 4])
ab = set([('x', 1), ('x', 2), ('x', 3), ('x', 4), ('y', 1), ('y', 2), ('y', 3), ('y', 4)])

AB = set(list(product(a,b)))                                     # 문제1. answer code here (should be 1 line using a and b)
A, B = set(list(zip(*AB))[0]), set(list(zip(*AB))[1])  # 문제2. answer code here (should be 1 line using AB)


print(f'ab == AB : {ab == AB}')
print(f'a == A : {a == A}')
print(f'b == B : {b == B}')

print(A)
print(B)
print(AB)

ab == AB : True
a == A : True
b == B : True
{'y', 'x'}
{1, 2, 3, 4}
{('y', 3), ('x', 2), ('y', 2), ('x', 3), ('y', 1), ('x', 1), ('x', 4), ('y', 4)}

# 8. regex, ngram (15 points)

온라인 쇼핑몰에서 특정 상품이름이 주어졌을 때, 
- 문제1. 상품 이름을 토크나이즈하는 function을 구현하시오
    - function은 다음 두개의 parameter를 받는다.
        - string : 토크나이즈할 문자열
        - split_by : 토큰을 구분할 list of characters
- 문제2. n gram을 만드는 function을 구현하시오
    - function은 다음 두개의 parameter를 받는다.
        - list_of_token : 토큰의 list  
        - n : n-gram의 n
- hint
    - re.escape
    - re.split
    - zip
        
        
```python


import re

def dummy_tokenizer(string, split_by):
    # implement function 
    pattern = ... # code here (should be 1 line)
    return ... # code here (should be 1 line)

def dummy_ngram(list_of_token, n):
    # implement function 
    return ... # code here (should be 1 line)

split_by = ['[', ']', ':', '+', ' ']
goods_name = '[[패키지 : 삼성 공기청정기]] [화이트 그랑데AI 패키지] 삼성 그랑데 AI 세탁기 21KG [WF21T6500KW] + 삼성 그랑데 AI 건조기 16KG [DV16T8740B'

list_of_token = dummy_tokenizer(goods_name, split_by)
n_gram = dummy_ngram(list_of_token, 7)

print(f'\ngoods_name : \n "{goods_name}"')
print(f'\nlist_of_token : \n {list_of_token}')
print('\nn gram :')
[print(g) for g in n_gram]

goods_name : 
"[[패키지 : 삼성 공기청정기]] [화이트 그랑데AI 패키지] 삼성 그랑데 AI 세탁기 21KG [WF21T6500KW] + 삼성 그랑데 AI 건조기 16KG [DV16T8740B"

list_of_token : 
['패키지', '삼성', '공기청정기', '화이트', '그랑데AI', '패키지', '삼성', '그랑데', 'AI', '세탁기', '21KG', 'WF21T6500KW', '삼성', '그랑데', 'AI', '건조기', '16KG', 'DV16T8740B']

n gram :
('패키지', '삼성', '공기청정기', '화이트', '그랑데AI', '패키지', '삼성')
('삼성', '공기청정기', '화이트', '그랑데AI', '패키지', '삼성', '그랑데')
('공기청정기', '화이트', '그랑데AI', '패키지', '삼성', '그랑데', 'AI')
('화이트', '그랑데AI', '패키지', '삼성', '그랑데', 'AI', '세탁기')
('그랑데AI', '패키지', '삼성', '그랑데', 'AI', '세탁기', '21KG')
('패키지', '삼성', '그랑데', 'AI', '세탁기', '21KG', 'WF21T6500KW')
('삼성', '그랑데', 'AI', '세탁기', '21KG', 'WF21T6500KW', '삼성')
('그랑데', 'AI', '세탁기', '21KG', 'WF21T6500KW', '삼성', '그랑데')
('AI', '세탁기', '21KG', 'WF21T6500KW', '삼성', '그랑데', 'AI')
('세탁기', '21KG', 'WF21T6500KW', '삼성', '그랑데', 'AI', '건조기')
('21KG', 'WF21T6500KW', '삼성', '그랑데', 'AI', '건조기', '16KG')
('WF21T6500KW', '삼성', '그랑데', 'AI', '건조기', '16KG', 'DV16T8740B')


```

# 답안

In [11]:
import re

def dummy_tokenizer(string, split_by):
    # implement function 
    pattern = '|'.join(map(re.escape, split_by))   # answer code here (should be 1 line)
    return re.sub(pattern,' ', string).split()          # answer code here (should be 1 line)

def dummy_ngram(list_of_token, n):
    # implement function 
    return list(zip(*[list_of_token[i:] for i in range(n)]))     # answer code here (should be 1 line)



split_by = ['[', ']', ':', '+', ' ']
goods_name = '[[패키지 : 삼성 공기청정기]] [화이트 그랑데AI 패키지] 삼성 그랑데 AI 세탁기 21KG [WF21T6500KW] + 삼성 그랑데 AI 건조기 16KG [DV16T8740B'

list_of_token = dummy_tokenizer(goods_name, split_by)
n_gram = dummy_ngram(list_of_token, 7)

print(f'\ngoods_name : \n "{goods_name}"')
print(f'\nlist_of_token : \n {list_of_token}')
print('\nn gram :')
[print(g) for g in n_gram]

goods_name :
 "[[패키지 : 삼성 공기청정기]] [화이트 그랑데AI 패키지] 삼성 그랑데 AI 세탁기 21KG [WF21T6500KW] + 삼성 그랑데 AI 건조기 16KG [DV16T8740B"

list_of_token :
 ['패키지', '삼성', '공기청정기', '화이트', '그랑데AI', '패키지', '삼성', '그랑데', 'AI', '세탁기', '21KG', 'WF21T6500KW', '삼성', '그랑데', 'AI', '건조기', '16KG', 'DV16T8740B']

n gram :
('패키지', '삼성', '공기청정기', '화이트', '그랑데AI', '패키지', '삼성')
('삼성', '공기청정기', '화이트', '그랑데AI', '패키지', '삼성', '그랑데')
('공기청정기', '화이트', '그랑데AI', '패키지', '삼성', '그랑데', 'AI')
('화이트', '그랑데AI', '패키지', '삼성', '그랑데', 'AI', '세탁기')
('그랑데AI', '패키지', '삼성', '그랑데', 'AI', '세탁기', '21KG')
('패키지', '삼성', '그랑데', 'AI', '세탁기', '21KG', 'WF21T6500KW')
('삼성', '그랑데', 'AI', '세탁기', '21KG', 'WF21T6500KW', '삼성')
('그랑데', 'AI', '세탁기', '21KG', 'WF21T6500KW', '삼성', '그랑데')
('AI', '세탁기', '21KG', 'WF21T6500KW', '삼성', '그랑데', 'AI')
('세탁기', '21KG', 'WF21T6500KW', '삼성', '그랑데', 'AI', '건조기')
('21KG', 'WF21T6500KW', '삼성', '그랑데', 'AI', '건조기', '16KG')
('WF21T6500KW', '삼성', '그랑데', 'AI', '건조기', '16KG', 'DV16T8740B')

[None, None, None, None, None, None, None, None, None, None, None, None]

# 9. funcrion definition, list manipulation, print formatting, ... (20 point)

- 문제1. 다음 정의에 부합하는 function f를 <span style="color:red">재귀함수(recursive function)</span>로 구현하시오. (순수 구현 부분은 <span style="color:red">1 line code</span>)
    - $ f(0) = 1 $
    - $ f(n) = n \cdot f(n-1) \quad where \quad n > 0 \quad 인 \quad 자연수 $


- 문제2. 다음 정의에 부합하는 function c를 구현하시오. (순수 구현 부분은 <span style="color:red">1 line code</span>)
    - $ c(n, r) = \frac{f(n)}{f(n-r) \cdot f(r)} $
    - $ c(n, r) $ 의 값은 자연수이어야 함. <span style="color:red">(즉, float type 일 수는 없음)</span>


- 문제3. 다음 정의에 부합하는 function b를 구현하시오. (순수 구현 부분은 <span style="color:red">1 line code</span>)
    - $ b(n) = [c(n, 0), c(n, 1), c(n, 2), ..., c(n, r), ..., c(n, n-1), c(n, n) ] $
    - $ b(n) $ 의 값은 n+1개의 자연수를 원소로 갖는 list 
        - $ b(0) == [1] $ 
        - $ b(1) == [1, 1] $ 
        - $ b(2) == [1, 2, 1] $ 
        - $ b(3) == [1, 3, 3, 1] $ 
        - $ b(4) == [1, 4, 6, 4, 1] $ 
        
- 문제4. 다음 정의에 부합하는 function t를 구현하시오. (순수 구현 부분은 <span style="color:red">1 line code</span>)
    - $ t(N) = [ b(0), b(1), b(2), ..., b(N) ] $
    - $ t(4) = [[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]] $ 
        
- 문제5.
    - 문제4의 t(N)의 결과를 입력으로 받아서 아래와 같이 삼각형 형태로 출력하는 function을 구현하시오
    - t(9)를 출력해 보시오

    
                             1
                           1   1
                         1   2   1
                       1   3   3   1
                     1   4   6   4   1
                   1   5  10  10   5   1
                 1   6  15  20  15   6   1
               1   7  21  35  35  21   7   1
             1   8  28  56  70  56  28   8   1
           1   9  36  84 126 126  84  36   9   1
       
    
- hint
    - range
    - f-string formatting (width specfy, center alignment)
    - list comprehension
    - recursive function definition
    - integer divide operator
    - value if ... else ...

```python

def f(n):
    return ... # code here (should be 1 line)

def c(n, r):
    return ... # code here (should be 1 line)
    
def b(n):
    return ... # code here (should be 1 line)
    
def t(N):
    return ... # code here (should be 1 line)

def print_triangle(tN):
    # code ...
    # line수 제한 없음
    # code ... 
    
print_triangle(t(9))
    
                    1                  
                  1   1                
                1   2   1              
              1   3   3   1            
            1   4   6   4   1          
          1   5  10  10   5   1        
        1   6  15  20  15   6   1      
      1   7  21  35  35  21   7   1    
    1   8  28  56  70  56  28   8   1  
  1   9  36  84 126 126  84  36   9   1

```

# 답안

In [12]:
def f(n):
    return n*f(n-1) if n>0 else 1# code here (should be 1 line)

def c(n, r):
    return  f(n)//(f(n-r)*f(r))# code here (should be 1 line)

def b(n):
    return [c(n,x) for x in range(n+1)] # code here (should be 1 line)

def t(N):
    return [b(x) for x in range(N+1)] # code here (should be 1 line)

def print_triangle(tN):
    
    # line수 제한 없음  # code here 
    for i,j in zip(range(1, len(tN)+1),tN):
        print("   "*(len(tN)-i),'   '.join(str(_) for _ in j))
    
    

print_triangle(t(9))

                            1
                         1   1
                      1   2   1
                   1   3   3   1
                1   4   6   4   1
             1   5   10   10   5   1
          1   6   15   20   15   6   1
       1   7   21   35   35   21   7   1
    1   8   28   56   70   56   28   8   1
 1   9   36   84   126   126   84   36   9   1